services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    entrypoint: >
      sh -c "test -f /mosquitto/config/mosquitto.conf ||
             echo '# Allow clients to connect without a username/password' > /mosquitto/config/mosquitto.conf &&
             echo 'allow_anonymous true' >> /mosquitto/config/mosquitto.conf &&
             echo '' >> /mosquitto/config/mosquitto.conf &&
             echo '# Default MQTT listener on port 1883' >> /mosquitto/config/mosquitto.conf &&
             echo 'listener 1883' >> /mosquitto/config/mosquitto.conf;
             mosquitto -c /mosquitto/config/mosquitto.conf"
    restart: always
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    depends_on:
      - mqtt
    restart: always
